# Generated by Django 3.0.2 on 2020-02-05 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ta',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to="cvs/%Y/%m/%d/"),
        ),
    ]
