# Generated by Django 3.0.2 on 2020-02-19 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20200205_0113'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankTA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('TA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.TA')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Course')),
            ],
        ),
    ]
