# Generated by Django 3.0.4 on 2020-03-20 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_rankcourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ta',
            name='availableHours',
        ),
        migrations.AddField(
            model_name='taduty',
            name='recommendedTANumber',
            field=models.IntegerField(default=0),
        ),
    ]
