# Generated by Django 3.0.4 on 2020-03-27 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20200320_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('value', models.IntegerField(default=0)),
                ('TA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.TA')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Course')),
            ],
        ),
    ]
