# Generated by Django 3.0.4 on 2020-03-27 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_matchresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmenthead',
            name='department',
            field=models.CharField(default='', max_length=20),
        ),
    ]
