# Generated by Django 3.0.4 on 2020-03-29 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_departmenthead_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchresult',
            old_name='value',
            new_name='TAValue',
        ),
        migrations.RemoveField(
            model_name='matchresult',
            name='position',
        ),
        migrations.AddField(
            model_name='matchresult',
            name='courseValue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ta',
            name='expectedCourseNumber',
            field=models.IntegerField(default=0, max_length=2),
        ),
    ]
