# Generated by Django 3.0.4 on 2020-03-29 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_auto_20200329_0027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchresult',
            old_name='TAValue',
            new_name='TARanking',
        ),
        migrations.RenameField(
            model_name='matchresult',
            old_name='courseValue',
            new_name='courseRanking',
        ),
        migrations.RenameField(
            model_name='rankcourse',
            old_name='value',
            new_name='ranking',
        ),
        migrations.RenameField(
            model_name='rankta',
            old_name='value',
            new_name='ranking',
        ),
        migrations.AlterField(
            model_name='ta',
            name='expectedCourseNumber',
            field=models.IntegerField(default=0),
        ),
    ]
