# Generated by Django 3.0.4 on 2020-03-30 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_auto_20200329_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchresult',
            name='positions',
            field=models.IntegerField(default=0),
        ),
    ]
