# Generated by Django 3.0.4 on 2020-04-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_matchresult_positions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ta',
            name='expectedCourseNumber',
        ),
        migrations.AddField(
            model_name='matchresult',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
